name: criu-static build
on:
  # Run on push events
  push:
    # Only run when code is pushed to these branches
    branches:
      - "master"
    # Avoid running when tags are pushed
    tags-ignore:
      - "**"
    # Avoid running when certain files are modified
    paths-ignore:
      - "docs/**"

  # Run on pull request events
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  # Manual trigger for custom builds and releases
  workflow_dispatch:
    inputs:
      criu_version:
        description: 'CRIU version to build (e.g., 4.1)'
        required: false
        type: string
      criu_commit:
        description: 'CRIU commit/tag to build (overrides version if set)'
        required: false
        type: string
      criu_shasum:
        description: 'SHA256 checksum for the CRIU source'
        required: true
        type: string
      build_revision:
        description: 'Build revision suffix (e.g., r1, r2) for build script changes'
        required: false
        type: string
      release_type:
        description: 'Release type'
        required: false
        type: choice
        default: 'draft'
        options:
          - 'none'
          - 'draft'
          - 'release'

# avoid running multiple copies of the same workflow in parallel
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-amd64:
    name: Build criu(amd64)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Build criu
        if: github.event_name != 'workflow_dispatch'
        uses: docker/build-push-action@v6
        with:
          context: .
          outputs: type=local,dest=./output
          file: Dockerfile
          push: false
          load: true
          tags: "criu-build-image-amd64"
          platforms: "linux/amd64"
          cache-from: type=gha,scope=criu-build-image-amd64
          cache-to: type=gha,mode=max,scope=criu-build-image-amd64

      - name: Build criu
        if: github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6
        with:
          context: .
          outputs: type=local,dest=./output
          file: Dockerfile
          push: false
          load: true
          tags: "criu-build-image-amd64"
          platforms: "linux/amd64"
          cache-from: type=gha,scope=criu-build-image-amd64
          cache-to: type=gha,mode=max,scope=criu-build-image-amd64
          build-args: |
            CRIU_VERSION=${{ inputs.criu_version }}
            CRIU_COMMIT=${{ inputs.criu_commit }}
            CRIU_SHASUM=${{ inputs.criu_shasum }}

      - name: Upload amd64 artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: criu-amd64
          path: ./output

  build-arm64:
    name: Build criu(arm64)
    runs-on: ubuntu-24.04-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Build criu
        if: github.event_name != 'workflow_dispatch'
        uses: docker/build-push-action@v6
        with:
          context: .
          outputs: type=local,dest=./output
          file: Dockerfile
          push: false
          load: true
          tags: "criu-build-image-arm64"
          platforms: "linux/arm64"
          cache-from: type=gha,scope=criu-build-image-arm64
          cache-to: type=gha,mode=max,scope=criu-build-image-arm64

      - name: Build criu
        if: github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6
        with:
          context: .
          outputs: type=local,dest=./output
          file: Dockerfile
          push: false
          load: true
          tags: "criu-build-image-arm64"
          platforms: "linux/arm64"
          cache-from: type=gha,scope=criu-build-image-arm64
          cache-to: type=gha,mode=max,scope=criu-build-image-arm64
          build-args: |
            CRIU_VERSION=${{ inputs.criu_version }}
            CRIU_COMMIT=${{ inputs.criu_commit }}
            CRIU_SHASUM=${{ inputs.criu_shasum }}

      - name: Upload arm64 artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: criu-arm64
          path: ./output

  release:
    name: Release
    if: "inputs.release_type != 'none'"
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Download build artifacts (amd64)
        uses: actions/download-artifact@v4.3.0
        with:
          pattern: criu-amd64
          path: dist

      - name: Download build artifacts (arm64)
        uses: actions/download-artifact@v4.3.0
        with:
          pattern: criu-arm64
          path: dist

      - name: Setup Java for JReleaser
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Determine version
        id: version
        run: |
          if [ -n "${{ inputs.criu_commit }}" ]; then
            BASE_VERSION="${{ inputs.criu_commit }}"
          elif [ -n "${{ inputs.criu_version }}" ]; then
            BASE_VERSION="${{ inputs.criu_version }}"
          else
            BASE_VERSION=$(cmake --preset static-release -LA  | grep CRIU_VERSION | cut -d'=' -f2)
          fi

          if [ -n "${{ inputs.build_revision }}" ]; then
            VERSION="${BASE_VERSION}-${{ inputs.build_revision }}"
          else
            VERSION="${BASE_VERSION}"
          fi

          echo "VERSION = $VERSION"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Run JReleaser
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ steps.version.outputs.VERSION }}
          JRELEASER_DRAFT: ${{ inputs.release_type == 'draft' }}
